### ISSUE TITLE
Nuxt 3 document is not defined when refresh

### ISSUE THREAD

**Issue by ldiellyoungl** [fumeapp/tailvue#13]
i use const $toast = useToast() in <script setup></script> section if i refresh page  then  document is not defined. but if i use $toast = useToast() in function and execute it toast and modals work is fine. what is my problem? sorry for bad english

**Comment by tcampbPPU** [comment]
Just so I understand correctly just declaring the composable like:
```ts
<script lang="ts" setup>
const $toast = useToast()
</script>
```
With Nuxt 3 you should do like this instead and be importing from `useNuxtApp`
```ts
<script lang="ts" setup>
import { useNuxtApp } from '#app'
const { $toast } = useNuxtApp()
</script>
```

**Comment by tcampbPPU** [comment]
You can see an example of this in our [Nuxt 3 Template](https://github.com/fumeapp/laranuxt/blob/main/client/components/session/SessionDevice.vue#L88) hopefully that helps out
