### ISSUE TITLE
Push button .stop modifier dont work

### ISSUE THREAD

**Issue by ldiellyoungl** [fumeapp/tailvue#14]
if i use .stop modifier on pushButton then dont work. what i can do?

**Comment by acidjazz** [comment]
i'm not really aware of a stop modifier - can you clarify?

**Comment by ldiellyoungl** [comment]
> i'm not really aware of a stop modifier - can you clarify?

https://vuejs.org/guide/essentials/event-handling.html#event-modifiers
.stop modifiet dont work. im using like this:
`<div @click.stop="do_parent()"><PushButton @click.stop="do_child()"></PushButton></div>`
nothing happens when i pressed PushButton

**Comment by tcampbPPU** [comment]
not sure event modifier work for the push button click that. The `@click` is not native Vue event but rather the click emit from the component itself see [here](https://github.com/fumeapp/tailvue/blob/main/src/PushButton.vue#L44)
