### ISSUE TITLE
Invalid ARIA attribute name: aria-alive

### ISSUE THREAD

**Issue by mukundshah** [fumeapp/tailvue#18]
https://github.com/fumeapp/tailvue/blob/6a061de16fa2f2690ecc03a470df2aaa34f1518f/src/toast.ts#L21

The right attribute is `aria-live="assertive"`

```ts
 outer.setAttribute('aria-live', 'assertive') 
```

**Comment by acidjazz** [comment]
Thanks! PR's are appreciated as well!
