### ISSUE TITLE
Feature suggestion - Add option to pause toast timeout when hovering

### ISSUE THREAD

**Issue by hfoletto** [fumeapp/tailvue#20]
I've been using this package with Nuxt 3 with great success!

This issue is just a suggestion to add an option (or make it the default) to pause the toast timeout when hovering.
In my specific case I use a danger toast to show errors/exceptions, and a 6 seconds is enough, but in some cases the message is very long, so it could be useful to pause the timeout when hovering.

Thank you!

**Comment by acidjazz** [comment]
Great idea  - i think this is possible by tracking a ref variable using `@mouseover` and `@mouseleave` on the top div [here](https://github.com/fumeapp/tailvue/blob/main/src/GlobalToast.vue#L3)

you can then intercept `updateTime` [here](https://github.com/fumeapp/tailvue/blob/main/src/GlobalToast.vue#L162-L165) and just `return` if that variable is true

happy to try this out when i get time - feel free to create a PR as well @hfoletto. !

**Comment by hfoletto** [comment]
Thank you @acidjazz! The PR is up #21
